// MISALIGNED chunk 2 (P8-P15): misaligned accesses interacting with interrupts, forwarding, wrong paths, mret, handlers.
// GENERATED by gen_mis2.py from tb_mis2_template.v -- edit the template/generator, not this file.
module tb_mis2();

reg clk, reset;
reg kb, dk;

top top_inst (.clk(clk), .reset(reset), .interrupt_keyboard(kb), .interrupt_disk(dk));

always #5 clk = ~clk;

wire [31:0] PC_EX = top_inst.PC_EX;
`define REG(n) top_inst.ID_stage_inst.register_file_inst.registers[n]

// ---- addresses taken from the generated program ----
localparam M8 = 364;
localparam M9 = 460;
localparam M10 = 560;
localparam M11 = 836;
localparam M12 = 1072;
localparam M13 = 1220;
localparam M14 = 1352;
localparam M15 = 1468;
localparam PARK = 1548;
localparam WP_LO = 868;
localparam WP_HI = 1052;
localparam P15A_LD = 1496;
localparam P15B_LD = 1516;
localparam P8A_N = 388;
localparam P8B_N = 404;
localparam P8C_N = 420;
localparam P9A_N = 488;
localparam H_CNT = 1628;
localparam P9B_N = 512;
localparam P13C_N = 1308;
localparam P14A_N = 1376;
localparam P14B_N = 1392;
localparam P14C_N = 1424;
localparam P15A_N = 1492;

localparam NEV = 41;

integer errors, ev_idx;
reg [31:0] exp_cause [0:NEV-1];
reg [31:0] exp_mepc  [0:NEV-1];
reg        chk_pend;            // verify the real mcause / mepc registers one cycle after each trap
reg [31:0] chk_cause, chk_pc;

// P11 wrong-path counters, P15 load-run counters
integer wp_id, wp_if, ld_runs_a, ld_runs_b;

task check;
    input [8*22-1:0] what;
    input integer got;
    input integer exp;
begin
    if (got !== exp) begin
        errors = errors + 1;
        $display("  [FAIL] %0s: got %0d (0x%08h), expected %0d (0x%08h)", what, got, got, exp, exp);
    end else
        $display("  [ ok ] %0s = %0d", what, got);
end
endtask

// state that must hold once a phase has fully unwound (called at the next phase's marker)
task phase_check;
    input [8*4-1:0] name;
    input integer post;
    input integer exp_exc;      // cumulative exception handler runs (x30)
    input integer exp_events;   // cumulative events logged (exceptions + interrupts)
    input integer exp_kb;       // cumulative keyboard ISR runs (x28)
    input integer exp_dk;       // cumulative disk ISR runs (x25)
integer idx0;
begin
    idx0 = ev_idx;
    @(negedge clk);
    $display("--- end of phase %0s (t=%0t) ---", name, $time);
    check("x21 (post marker)",  `REG(21), post);
    check("x6  (live)",         `REG(6),  111);
    check("x7  (live)",         `REG(7),  222);
    check("sp (x2)",            `REG(2),  200);
    check("x30 trap count",     `REG(30), exp_exc);
    check("x28 kb ISR count",   `REG(28), exp_kb);
    check("x25 disk ISR count", `REG(25), exp_dk);
    check("events logged",      idx0,     exp_events);
    check("mie",                top_inst.mie_val, 1);
    check("mpie",               top_inst.mpie_val, 1);
    check("current_priority",   top_inst.current_priority_val, 0);
    check("previous_priority",  top_inst.previous_priority_val, 0);
end
endtask

initial begin
    // {cause, mepc} in program order. Exceptions: 4 load / 6 store misaligned, 2 illegal. Interrupts: 0x80000007 keyboard, 0x8000001b disk.
    exp_cause[0] = 32'h80000007; exp_mepc[0] = 392;
    exp_cause[1] = 32'h00000004; exp_mepc[1] = 392;
    exp_cause[2] = 32'h80000007; exp_mepc[2] = 408;
    exp_cause[3] = 32'h00000006; exp_mepc[3] = 408;
    exp_cause[4] = 32'h80000007; exp_mepc[4] = 424;
    exp_cause[5] = 32'h00000004; exp_mepc[5] = 424;
    exp_cause[6] = 32'h00000004; exp_mepc[6] = 492;
    exp_cause[7] = 32'h80000007; exp_mepc[7] = 496;
    exp_cause[8] = 32'h00000006; exp_mepc[8] = 516;
    exp_cause[9] = 32'h80000007; exp_mepc[9] = 520;
    exp_cause[10] = 32'h00000004; exp_mepc[10] = 596;
    exp_cause[11] = 32'h00000004; exp_mepc[11] = 620;
    exp_cause[12] = 32'h00000004; exp_mepc[12] = 640;
    exp_cause[13] = 32'h00000006; exp_mepc[13] = 660;
    exp_cause[14] = 32'h00000006; exp_mepc[14] = 684;
    exp_cause[15] = 32'h00000006; exp_mepc[15] = 704;
    exp_cause[16] = 32'h00000004; exp_mepc[16] = 972;
    exp_cause[17] = 32'h00000006; exp_mepc[17] = 1000;
    exp_cause[18] = 32'h00000004; exp_mepc[18] = 1028;
    exp_cause[19] = 32'h00000004; exp_mepc[19] = 1028;
    exp_cause[20] = 32'h00000004; exp_mepc[20] = 1104;
    exp_cause[21] = 32'h00000006; exp_mepc[21] = 1148;
    exp_cause[22] = 32'h00000004; exp_mepc[22] = 1244;
    exp_cause[23] = 32'h00000004; exp_mepc[23] = 1668;
    exp_cause[24] = 32'h00000006; exp_mepc[24] = 1672;
    exp_cause[25] = 32'h00000006; exp_mepc[25] = 1276;
    exp_cause[26] = 32'h00000004; exp_mepc[26] = 1668;
    exp_cause[27] = 32'h00000006; exp_mepc[27] = 1672;
    exp_cause[28] = 32'h80000007; exp_mepc[28] = 1312;
    exp_cause[29] = 32'h00000004; exp_mepc[29] = 1836;
    exp_cause[30] = 32'h00000006; exp_mepc[30] = 1840;
    exp_cause[31] = 32'h8000001b; exp_mepc[31] = 1380;
    exp_cause[32] = 32'h00000004; exp_mepc[32] = 1380;
    exp_cause[33] = 32'h8000001b; exp_mepc[33] = 1396;
    exp_cause[34] = 32'h00000006; exp_mepc[34] = 1396;
    exp_cause[35] = 32'h8000001b; exp_mepc[35] = 1428;
    exp_cause[36] = 32'h00000004; exp_mepc[36] = 1996;
    exp_cause[37] = 32'h00000006; exp_mepc[37] = 2000;
    exp_cause[38] = 32'h80000007; exp_mepc[38] = 1496;
    exp_cause[39] = 32'h00000002; exp_mepc[39] = 1500;
    exp_cause[40] = 32'h00000002; exp_mepc[40] = 1520;
end

task log_event;
    input [31:0] cause;
    input [31:0] pc;
    input [8*3-1:0] src;
begin
    $display(">>> EVT #%0d cause=0x%08h mepc=%0d src=%0s t=%0t", ev_idx, cause, pc, src, $time);
    if (ev_idx >= NEV) begin
        errors = errors + 1;
        $display("  [FAIL] unexpected extra event");
    end else if (cause !== exp_cause[ev_idx] || pc !== exp_mepc[ev_idx]) begin
        errors = errors + 1;
        $display("  [FAIL] event #%0d expected cause=0x%08h mepc=%0d", ev_idx, exp_cause[ev_idx], exp_mepc[ev_idx]);
    end
    chk_pend = 1'b1; chk_cause = cause; chk_pc = pc;
    ev_idx = ev_idx + 1;
end
endtask

// Trap monitor. The vector and the stored CSRs are computed in different places, so the stored values are checked too.
always @(negedge clk) begin
    if (!reset) begin
        if (chk_pend) begin
            chk_pend = 1'b0;
            if (top_inst.mcause_val !== chk_cause || top_inst.mepc_val !== chk_pc) begin
                errors = errors + 1;
                $display("  [FAIL] stored CSRs: mcause=0x%08h mepc=%0d, trap used cause=0x%08h mepc=%0d",
                         top_inst.mcause_val, top_inst.mepc_val, chk_cause, chk_pc);
            end
        end
        if (top_inst.exception_taken_EX && top_inst.exception_taken_ID) begin
            errors = errors + 1;
            $display(">>> [FAIL] EX and ID exception signals high together");
        end
        if (top_inst.interrupt_taken && top_inst.exception_taken) begin
            errors = errors + 1;
            $display(">>> [FAIL] interrupt and exception signals high together");
        end
        if (top_inst.interrupt_taken)
            log_event(top_inst.mcause_next, PC_EX, "INT");
        else if (top_inst.exception_taken_EX)
            log_event(top_inst.mcause_next, PC_EX, "EX");
        else if (top_inst.exception_taken)
            log_event(top_inst.mcause_next, top_inst.PC_ID, "ID");

        // P11: count the cycles in which a branch/jump redirect flushes a load/store that sits in ID (first slot) / IF (second slot).
        // Only redirects whose branch/jump itself lies in the P11 code window count.
        if (top_inst.EX_Override_EX && PC_EX >= WP_LO && PC_EX < WP_HI) begin
            if (top_inst.Instr_ID[6:0] == 7'b0000011 || top_inst.Instr_ID[6:0] == 7'b0100011) wp_id = wp_id + 1;
            if (top_inst.Instr_IF[6:0] == 7'b0000011 || top_inst.Instr_IF[6:0] == 7'b0100011) wp_if = wp_if + 1;
        end

        // P15: the load must complete (not be squashed) exactly once
        if (PC_EX == P15A_LD && !top_inst.interrupt_taken && !top_inst.exception_taken_EX) ld_runs_a = ld_runs_a + 1;
        if (PC_EX == P15B_LD && !top_inst.interrupt_taken && !top_inst.exception_taken_EX) ld_runs_b = ld_runs_b + 1;
    end
end

// ---- interrupt pulses (1 cycle each). A pulse at PC_EX == X is taken with EX = X+4 (mepc = X+4). ----
initial begin wait (PC_EX == M8); wait (PC_EX == P8A_N); @(negedge clk); kb = 1'b1; @(negedge clk); kb = 1'b0; end
initial begin wait (PC_EX == M8); wait (PC_EX == P8B_N); @(negedge clk); kb = 1'b1; @(negedge clk); kb = 1'b0; end
initial begin wait (PC_EX == M8); wait (PC_EX == P8C_N); @(negedge clk); kb = 1'b1; @(negedge clk); kb = 1'b0; end
initial begin wait (PC_EX == P9A_N); wait (PC_EX == H_CNT); @(negedge clk); kb = 1'b1; @(negedge clk); kb = 1'b0; end
initial begin wait (PC_EX == P9B_N); wait (PC_EX == H_CNT); @(negedge clk); kb = 1'b1; @(negedge clk); kb = 1'b0; end
initial begin wait (PC_EX == M13); wait (PC_EX == P13C_N); @(negedge clk); kb = 1'b1; @(negedge clk); kb = 1'b0; end
initial begin wait (PC_EX == M14); wait (PC_EX == P14A_N); @(negedge clk); dk = 1'b1; @(negedge clk); dk = 1'b0; end
initial begin wait (PC_EX == M14); wait (PC_EX == P14B_N); @(negedge clk); dk = 1'b1; @(negedge clk); dk = 1'b0; end
initial begin wait (PC_EX == M14); wait (PC_EX == P14C_N); @(negedge clk); dk = 1'b1; @(negedge clk); dk = 1'b0; end
initial begin wait (PC_EX == M15); wait (PC_EX == P15A_N); @(negedge clk); kb = 1'b1; @(negedge clk); kb = 1'b0; end

initial begin
    #80000;
    $display("---WATCHDOG FIRED--- PC_EX=%0d x30=%0d x28=%0d x25=%0d ev_idx=%0d", PC_EX, `REG(30), `REG(28), `REG(25), ev_idx);
    $display("=== WATCHDOG: TEST DID NOT FINISH ===");
    $finish;
end

initial begin
    reset = 1'b1; clk = 1'b0; kb = 1'b0; dk = 1'b0;
    errors = 0; ev_idx = 0; chk_pend = 1'b0;
    wp_id = 0; wp_if = 0; ld_runs_a = 0; ld_runs_b = 0;
    #23 reset = 1'b0;

    wait (PC_EX == M9);  phase_check("P8", 8, 3, 6, 3, 0);
        check("x14 sentinel", `REG(14), 32'h00000072);
        check("x15 sentinel", `REG(15), 32'h00000073);
        check("mem[80] intact", `REG(22), 32'h04030201);
        check("x26 kb mcause", `REG(26), 32'h80000007);
        check("x27 handler cause", `REG(27), 32'h00000004);
        check("x3 sentinel", `REG(3), 32'h00000033);
    wait (PC_EX == M10);  phase_check("P9", 9, 5, 10, 5, 0);
        check("x14 sentinel", `REG(14), 32'h00000072);
        check("x15 ran once", `REG(15), 32'h00000001);
        check("x16 ran once", `REG(16), 32'h00000001);
        check("mem[80] intact", `REG(22), 32'h04030201);
        check("x26 kb mcause", `REG(26), 32'h80000007);
        check("x27 handler cause", `REG(27), 32'h00000006);
    wait (PC_EX == M11);  phase_check("P10", 10, 11, 16, 5, 0);
        check("x14 sentinel", `REG(14), 32'h00000072);
        check("x15 lh ctl", `REG(15), 32'h00000403);
        check("x16 lw ctl", `REG(16), 32'h04030201);
        check("x17 lh ctl", `REG(17), 32'h00000403);
        check("mem[80] intact", `REG(22), 32'h04030201);
        check("mem[84] sh ctl", `REG(23), 32'h006b0201);
        check("mem[88] intact", `REG(1), 32'h04030201);
        check("x27 handler cause", `REG(27), 32'h00000006);
    wait (PC_EX == M12);  phase_check("P11", 11, 15, 20, 5, 0);
        check("x14 sentinel", `REG(14), 32'h00000072);
        check("x17 sentinel", `REG(17), 32'h00000075);
        check("x16 jumps ran", `REG(16), 32'h00000002);
        check("x24 wrong-path", `REG(24), 32'h00000000);
        check("x27 handler cause", `REG(27), 32'h00000004);
        check("wrong-path in ID", wp_id, 4);
        check("wrong-path in IF", wp_if, 3);
    wait (PC_EX == M13);  phase_check("P12", 12, 17, 22, 5, 0);
        check("x14 sentinel", `REG(14), 32'h00000072);
        check("x15 after mret", `REG(15), 32'h00000002);
        check("x31 cp (load)", `REG(22), 32'h00000001);
        check("x31 cp (store)", `REG(31), 32'h00000001);
        check("mem[80] intact", `REG(23), 32'h04030201);
        check("x27 handler cause", `REG(27), 32'h00000006);
    wait (PC_EX == M14);  phase_check("P13", 13, 25, 31, 6, 0);
        check("x14 sentinel", `REG(14), 32'h00000072);
        check("x3 sentinel", `REG(3), 32'h00000033);
        check("x4 consumed", `REG(4), 32'h00000000);
        check("mem[80] intact", `REG(22), 32'h04030201);
        check("x26 kb mcause", `REG(26), 32'h80000007);
        check("x27 handler cause", `REG(27), 32'h00000006);
    wait (PC_EX == M15);  phase_check("P14", 14, 29, 38, 6, 3);
        check("x14 sentinel", `REG(14), 32'h00000072);
        check("x15 sentinel", `REG(15), 32'h00000073);
        check("x3 sentinel", `REG(3), 32'h00000033);
        check("x31 cp in disk ISR", `REG(31), 32'h00000002);
        check("mem[80] intact", `REG(22), 32'h04030201);
        check("x26 dk mcause", `REG(26), 32'h8000001b);
        check("x27 handler cause", `REG(27), 32'h00000006);
    wait (PC_EX == PARK);  phase_check("P15", 15, 31, 41, 7, 3);
        check("x13 load result", `REG(13), 32'h04030201);
        check("x15 load result", `REG(15), 32'h04030201);
        check("x26 kb mcause", `REG(26), 32'h80000007);
        check("x27 handler cause", `REG(27), 32'h00000002);
        check("P15a load runs", ld_runs_a, 1);
        check("P15b load runs", ld_runs_b, 1);

    if (errors == 0) $display("=== ALL CHECKS PASSED ===");
    else             $display("=== %0d CHECK(S) FAILED ===", errors);
    $finish;
end

endmodule